# Generated by Django 5.2.9 on 2025-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitudausencia_url_justificativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudausencia',
            name='contacto_emergencia',
            field=models.CharField(default='00000', max_length=200, verbose_name='Contacto de Emergencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='correo_contacto',
            field=models.EmailField(default='sin@correo.com', max_length=254, verbose_name='Correo de Contacto'),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
